services:
  - type: web
    name: spring-app
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: '-Xmx512m'
