apiVersion: v1
kind: Secret
metadata:
  namespace: app
  name: credentials-artemis
type: Opaque
stringData:
  username: admin
  password: 'admin'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      containers:
        - name: artemis-mq
          image: apache/activemq-artemis:2.40.0
          env:
            - name: ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: credentials-artemis
                  key: username
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials-artemis
                  key: password
          ports:
            - containerPort: 61616
            - containerPort: 8161
          volumeMounts:
            - name: data
              mountPath: /var/lib/artemis-instance
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: artemis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  namespace: app
spec:
  selector:
    app: artemis
  ports:
    - name: artemis
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
