apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: stats
  labels:
    app: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: juanmaespi7/tecnoshop-consumer:latest
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
  namespace: stats
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
